import Link from 'next/link';
import type { Metadata } from 'next';
import MoviesList from '../components/MoviesList';
import { fetchMovies } from '../services/movieService';

export const metadata: Metadata = {
  title: 'Movies List',
  description: 'Generated by create next app'
};

const MoviesPage = async () => {
  const moviesData = await fetchMovies();

  return (
    <div className='page_wrapper'>
      {moviesData.results.map((movie: { id: string; title: string; poster_path: string }) => (
        <div key={movie.id}>
          <Link href={`/movies/${movie.id}`}>
            <MoviesList title={movie.title} poster_path={movie.poster_path} />
          </Link>
        </div>
      ))}
    </div>
  );
};

export default MoviesPage;
